language: java
jdk: oraclejdk8

# Define the services to use
services:
  - docker

before_install:
  - sudo service mysql stop
  - docker pull takimatraining/devops-training-db
  - docker run -d -p 127.0.0.1:3306:3306 takimatraining/devops-training-db

# Run Unit Test and Integration Tests
script:
  - mvn verify

  # Cache the .m2 folder to prevent redownloading dependencies on each build
cache:
  directories:
  - "$HOME/.m2/repository"


# Environment variables are strings (double quotes)
# Example:
# - secure: "DpR1th9rZvLMX0......"
env:
  global:
    - secure: "iDLrRtJOGoUYiGITlxrSKYSk9UGRauVungTIPgz87O8f0TvZZBCmI/utVcclZD2WEwvaFS7jmRzn4Dk9GXz9DAL/exwiK/+eYIa/I3N46SEV2uE1o+XasIUn2MeuLtbdierbvoN7Gb3wlZ1f9G5n/hkRPi3zbgb6GCkHou4F9o9s/w0iWUfFhHC0sLDbDzk+LsPkAWJzspAkIc8NU7PnAjFzVBqOwS6Rosh2dH1v32z7a/6x7VKGQEgSJxjf+PbKE5l4xoiVpfAdPVIRy492IbAgJsgCxWrTSDnLkeq35KsaZl8Wxc6pRbX+zxHL89mKyu7MXGPE0icoFqytslkH96C/fOCxy00W9Ie/Q/MedFZ+NMnLiLRicvguRvExSQeqIErPS5MVZd8pALuKZVG4dhJTB+08Pq+0p+5XLdjUmaq0HtJThM/Tu99qN/qByeWiFhp7MfsVHc2+EXICL8O6xhMyWcov4LQrE2b1iRI5FjffiZ+RUHwW3aFJct+FovXqIXaLWoH+6Qa6zy1uaQHZq/zniJiV1JHQ8qMvrxP9efJRmv0H05XNU1+rPJo9QmaS27SkBB4FyaoEZZyVY1gegrDG4ytDZQkGp8pZ82RKtGBz146LAK/T8zmdU3GDgBvGc9TpYagzduEsCJWvYynUVFED415WDSIYapNEYa+gtoE="

# The pipe (|) is useful to create multiline scripts
SONAR_TOKEN=9e0c45fa10947b836ed2c9b2dfcc3e0d95475498
script:
  - |
    mvn clean install sonar:sonar \
    -Dsonar.projectKey=jfraubbain_sample-application-students \
    -Dsonar.organization=jfraubbain-github \
    -Dsonar.host.url=https://sonarcloud.io \
    -Dsonar.login=9e0c45fa10947b836ed2c9b2dfcc3e0d95475498
